name: Armonía Learning Hub
favicon: null
layout_spectrum: 0.49906
typography_spectrum: 0.32015
title: Armonía Learning Hub
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000100'
    - '#ffffff'
    - '#21176d'
    - '#67322c'
    - '#f7a7a1'
  brandStrength: 0
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
